version: '2'
services:
  oms-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/oms/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=oms
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
